package com.safety.recognition.cassandra.repository.indexes;

import com.safety.recognition.cassandra.model.indexes.CrimesByStreetAndCategoryIndexKey;
import com.safety.recognition.cassandra.model.indexes.CrimesByStreetAndCategoryLast3MonthsIndex;
import org.springframework.data.cassandra.repository.CassandraRepository;

public interface CrimesByStreetAndCategoryLast3MonthsIndexRepository extends CassandraRepository<CrimesByStreetAndCategoryLast3MonthsIndex, CrimesByStreetAndCategoryIndexKey> {
}
