package com.safety.recognition.cassandra.repository.indexes;

import com.safety.recognition.cassandra.model.indexes.CrimesByNeighbourhoodAndCategoryAllTimeIndex;
import com.safety.recognition.cassandra.model.indexes.CrimesByNeighbourhoodAndCategoryIndexKey;
import org.springframework.data.cassandra.repository.CassandraRepository;

public interface CrimesByNeighbourhoodAndCategoryAllTimeIndexRepository extends CassandraRepository<CrimesByNeighbourhoodAndCategoryAllTimeIndex, CrimesByNeighbourhoodAndCategoryIndexKey> {
}
