package com.safety.recognition.cassandra.repository.indexes;

import com.safety.recognition.cassandra.model.indexes.CrimesByStreetAndCategoryIndexKey;
import com.safety.recognition.cassandra.model.indexes.CrimesByStreetAndCategoryLastYearIndex;
import org.springframework.data.cassandra.repository.CassandraRepository;

public interface CrimesByStreetAndCategoryLastYearIndexRepository extends CassandraRepository<CrimesByStreetAndCategoryLastYearIndex, CrimesByStreetAndCategoryIndexKey> {
}
