apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: indexes-calculator
spec:
  selector:
    matchLabels:
      app: indexes-calculator
  replicas: 5 # tells deployment to run 3 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: indexes-calculator
      annotations:
        # Just add these annotations to configure Prometheus.
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port:  "8080"
    spec:
      containers:
        - name: indexes-calculator
          image: michalkoszalka/indexes-calculator:latest
          ports:
            - containerPort: 8080
              name: server
            - containerPort: 8081
              name: management
          env:
            - name: KAFKA_BOOTSTRAP
              value: kafka-2.kafka-svc.default.svc.cluster.local:9093
            - name: CASSANDRA_HOST
              value: cassandra-0.cassandra.default.svc.cluster.local
            - name: CASSANDRA_PORT
              value: "9042"
            - name: SERVER_PORT
              value: "8080"
          resources:
            requests:
              memory: "2Gi"
              cpu: 1000m