apiVersion: extensions/v1beta1
kind: Deployment
metadata:
name: prediction-calculator
spec:
replicas: 1
template:
    metadata:
    labels:
        app: prediction-calculator
    spec:
    containers:
    - name: prediction-calculator
        image: michalkoszalka/prediction-calculator
        ports:
        - containerPort: 8090