FROM java:8
VOLUME /tmp
ADD target/safety-level-scheduler-1.0-SNAPSHOT.jar target/app.jar
RUN bash -c 'touch target/app.jar'
ENTRYPOINT ["java","-jar","-Dspring.profiles.active=local","target/app.jar"]
