apiVersion: extensions/v1beta1
kind: Deployment
metadata:
name: safety-push-notification-server-deployment
spec:
replicas: 1
template:
    metadata:
    labels:
        app: safety-push-notification-server
    spec:
    containers:
    - name: safety-push-notification-server
        image: michalkoszalka/safety-push-notification-server
        ports:
        - containerPort: 8090