version: '3'
services:
  cassandra:
    container_name: cassandra
    image: launcher.gcr.io/google/cassandra3
    environment:
      CASSANDRA_PROMETHEUS_ENABLED: 'true'
      JMX_EXPORTER_CONFIG: /var/lib/cassandra/prometheus.yaml
    volumes:
      - ./prometheus.yaml:/var/lib/cassandra/prometheus.yaml
    ports:
      - '7000:7000'
      - '7001:7001'
      - '7199:7199'
      - '9042:9042'
      - '9160:9160'
      - '9404:9404'

