---
apiVersion: v1
kind: Service
metadata:
  name: dev-kafka
  namespace: default
  labels:
    app: dev-kafka
spec:
  type: "ClusterIP"
  ports:
    - port: 9092
      name: kafka-port
      targetPort: 9092
      protocol: TCP
    - port: 9080
      name: kafdrop-port
      targetPort: 9010
      protocol: TCP
    - port: 8082
      name: kafka-rest-port
      targetPort: 8082
      protocol: TCP
  selector:
    app: dev-kafka
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dev-kafka
  namespace: default
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: dev-kafka
    spec:
      containers:
        - name: dev-kafka
          image: wurstmeister/kafka
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: dev-kafka
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: localhost:2181
        - name: zookeeper
          image: digitalwonderland/zookeeper
        - name: kafdrop
          image: thomsch98/kafdrop
          ports:
            - containerPort: 9010
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: ZK_HOSTS
              value: localhost:2181
            - name: LISTEN
              value: "9010"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kafdrop
  namespace: default
  annotations:
    ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
    - host: kafdrop.default.io
      http:
        paths:
          - path: /
            backend:
              serviceName: dev-kafka
              servicePort: 9080